import { env } from '../../config.ts'

export const adminAddr: string =
    env === 'dev'
        ? 'CB2MYSJFLTUMGRURINUT3B5A7VK45LNZWFRTLG2SJGBRVAQF32UDDUEX34'
        : 'FF6ZFKQWOZNGUGXFKOBH5WFAPY6SWSLKIIW52G64CQUKZWU52TN3BNMJPU'
